# Generated by Django 5.2.6 on 2025-09-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('session', 'student')},
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='device_fingerprint',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('session', 'device_fingerprint'), ('session', 'student')},
        ),
    ]
